services:
  web:
    # build the image
    build: .
    ports:
      - "8000:8000"
    # Add command for make migraions and migrate
    command: >
      bash -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    depends_on:
      - database
    env_file:
      - web_config.env
    container_name: web
  database:
    image: postgres:13
    env_file:
      - db_config.env
    expose:
      - "5432"
    ports:
      - "5433:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    command: -p 5432
    container_name: database
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    container_name: redis
volumes:
  postgresql_data: