services:
  web:
    image: advance_django
    ports:
      - "8000:8000"
    # Add command for make migraions and migrate
    command: >
      bash -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    depends_on:
      - database
    env_file:
      - web_config.env
  database:
    image: postgres:13
    env_file:
      - db_config.env
    expose:
      - "5433"
    ports:
      - "5433:5433"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    command: -p 5433
volumes:
  postgresql_data: